export type TriviaCategory =
  | 'geography'
  | 'science'
  | 'history'
  | 'culture'
  | 'sport'
  | 'nature'

import type { Difficulty } from '../difficulty'

export interface TriviaQuestion {
  id: string
  /** A magyar fordítás később kerül bele; a szerkezet már most készen áll rá. */
  prompt: { en: string; hu?: string }
  choices: { en: string[]; hu?: string[] }
  correctIndex: number
  category: TriviaCategory
  difficulty: Difficulty
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // ─────────────────────────────── MEDIUM ───────────────────────────────
  {
    id: 'geo-danube-countries',
    prompt: { en: 'Which river flows through the most countries?' },
    choices: { en: ['Danube', 'Nile', 'Amazon', 'Rhine'] },
    correctIndex: 0,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-longest-coastline',
    prompt: { en: 'Which country has the longest coastline?' },
    choices: { en: ['Russia', 'Canada', 'Indonesia', 'Australia'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-largest-landlocked',
    prompt: { en: 'What is the largest landlocked country by area?' },
    choices: { en: ['Mongolia', 'Chad', 'Kazakhstan', 'Bolivia'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-sea-without-coast',
    prompt: { en: 'Which sea has no coastline at all?' },
    choices: { en: ['Coral Sea', 'Aral Sea', 'Baltic Sea', 'Sargasso Sea'] },
    correctIndex: 3,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-most-unesco',
    prompt: { en: 'Which country has the most UNESCO World Heritage sites?' },
    choices: { en: ['China', 'Italy', 'Spain', 'France'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'sci-highest-melting-metal',
    prompt: { en: 'Which metal has the highest melting point?' },
    choices: { en: ['Platinum', 'Titanium', 'Tungsten', 'Iridium'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-octopus-hearts',
    prompt: { en: 'How many hearts does an octopus have?' },
    choices: { en: ['One', 'Two', 'Three', 'Four'] },
    correctIndex: 2,
    category: 'nature',
    difficulty: 'medium',
  },
  {
    id: 'sci-absolute-zero',
    prompt: { en: 'What is absolute zero in degrees Celsius?' },
    choices: { en: ['−273.15', '−459.67', '−196.00', '−100.00'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-shortest-day',
    prompt: { en: 'Which planet has the shortest day?' },
    choices: { en: ['Mercury', 'Mars', 'Venus', 'Jupiter'] },
    correctIndex: 3,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-cern-2012',
    prompt: { en: 'Which particle was confirmed at CERN in 2012?' },
    choices: { en: ['Neutrino', 'Higgs boson', 'Top quark', 'Muon'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'his-suleiman',
    prompt: { en: 'Which empire did Suleiman the Magnificent rule?' },
    choices: { en: ['Persian', 'Mughal', 'Ottoman', 'Byzantine'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'his-first-roman-emperor',
    prompt: { en: 'Who was the first Roman emperor?' },
    choices: { en: ['Julius Caesar', 'Augustus', 'Tiberius', 'Nero'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'his-turkey-republic',
    prompt: { en: 'In which year was the Republic of Turkey proclaimed?' },
    choices: { en: ['1908', '1918', '1923', '1930'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'cul-solitude',
    prompt: { en: 'Who wrote One Hundred Years of Solitude?' },
    choices: {
      en: ['Jorge Luis Borges', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Pablo Neruda'],
    },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-rite-of-spring',
    prompt: { en: 'Who composed The Rite of Spring?' },
    choices: { en: ['Claude Debussy', 'Igor Stravinsky', 'Maurice Ravel', 'Béla Bartók'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-seven-samurai',
    prompt: { en: 'Who directed Seven Samurai?' },
    choices: { en: ['Yasujirō Ozu', 'Akira Kurosawa', 'Kenji Mizoguchi', 'Masaki Kobayashi'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-hungarian-family',
    prompt: { en: 'Which language family does Hungarian belong to?' },
    choices: { en: ['Indo-European', 'Turkic', 'Uralic', 'Caucasian'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'spo-snooker-max',
    prompt: { en: 'What is the maximum break in snooker?' },
    choices: { en: ['140', '147', '155', '180'] },
    correctIndex: 1,
    category: 'sport',
    difficulty: 'medium',
  },

  {
    id: 'geo-mediterranean-island',
    prompt: { en: 'What is the largest island in the Mediterranean?' },
    choices: { en: ['Sardinia', 'Sicily', 'Cyprus', 'Corsica'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-europe-asia-range',
    prompt: { en: 'Which mountain range marks the border between Europe and Asia?' },
    choices: { en: ['Caucasus', 'Carpathians', 'Urals', 'Altai'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-morocco-capital',
    prompt: { en: 'What is the capital of Morocco?' },
    choices: { en: ['Casablanca', 'Marrakesh', 'Rabat', 'Fez'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-asia-desert',
    prompt: { en: 'What is the largest desert in Asia?' },
    choices: { en: ['Karakum', 'Gobi', 'Thar', 'Taklamakan'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-fire-and-ice',
    prompt: { en: 'Which country is nicknamed the Land of Fire and Ice?' },
    choices: { en: ['Norway', 'Iceland', 'Greenland', 'Chile'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-africa-population',
    prompt: { en: 'Which African country has the largest population?' },
    choices: { en: ['Egypt', 'Ethiopia', 'Nigeria', 'South Africa'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'sci-potassium-symbol',
    prompt: { en: 'What is the chemical symbol for potassium?' },
    choices: { en: ['P', 'Pt', 'K', 'Po'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-largest-organ',
    prompt: { en: 'What is the largest organ of the human body?' },
    choices: { en: ['Liver', 'Skin', 'Lungs', 'Intestine'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-main-atmosphere-gas',
    prompt: { en: "What is the most abundant gas in Earth's atmosphere?" },
    choices: { en: ['Oxygen', 'Nitrogen', 'Carbon dioxide', 'Hydrogen'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-ascorbic-acid',
    prompt: { en: 'Which vitamin is also called ascorbic acid?' },
    choices: { en: ['Vitamin A', 'Vitamin B6', 'Vitamin C', 'Vitamin E'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-earthquake-study',
    prompt: { en: 'What is the study of earthquakes called?' },
    choices: { en: ['Geodesy', 'Seismology', 'Volcanology', 'Tectonics'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-great-red-spot',
    prompt: { en: 'Which planet has the Great Red Spot?' },
    choices: { en: ['Mars', 'Saturn', 'Jupiter', 'Neptune'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'his-liberty-gift',
    prompt: { en: 'Which country gave the Statue of Liberty to the United States?' },
    choices: { en: ['Britain', 'France', 'Spain', 'Netherlands'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'his-olympics-origin',
    prompt: { en: 'In which country did the Olympic Games originate?' },
    choices: { en: ['Italy', 'Egypt', 'Greece', 'Turkey'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'his-most-pyramids',
    prompt: { en: 'Which country has the most pyramids?' },
    choices: { en: ['Egypt', 'Mexico', 'Sudan', 'Peru'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'cul-orwell-1984',
    prompt: { en: 'Who wrote Nineteen Eighty-Four?' },
    choices: { en: ['Aldous Huxley', 'George Orwell', 'H. G. Wells', 'Ray Bradbury'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-starry-night',
    prompt: { en: 'Who painted The Starry Night?' },
    choices: { en: ['Claude Monet', 'Paul Cezanne', 'Vincent van Gogh', 'Edvard Munch'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-prado',
    prompt: { en: 'In which city is the Prado Museum?' },
    choices: { en: ['Barcelona', 'Lisbon', 'Madrid', 'Seville'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'medium',
  },

  // ──────────────────────────────── HARD ────────────────────────────────
  {
    id: 'geo-most-time-zones',
    prompt: { en: 'Which country spans the most time zones?' },
    choices: { en: ['Russia', 'France', 'United States', 'United Kingdom'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-doubly-landlocked',
    prompt: { en: 'Which country is doubly landlocked, surrounded only by landlocked states?' },
    choices: { en: ['Mongolia', 'Nepal', 'Uzbekistan', 'Bolivia'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-southernmost-capital',
    prompt: { en: 'Which is the southernmost national capital in the world?' },
    choices: { en: ['Canberra', 'Santiago', 'Buenos Aires', 'Wellington'] },
    correctIndex: 3,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-baikal-share',
    prompt: {
      en: "Roughly what share of the world's unfrozen fresh surface water sits in Lake Baikal?",
    },
    choices: { en: ['5%', '10%', '20%', '40%'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-bosphorus',
    prompt: { en: 'Which strait connects the Black Sea to the Sea of Marmara?' },
    choices: { en: ['Dardanelles', 'Bosphorus', 'Kerch Strait', 'Strait of Messina'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'sci-most-abundant-protein',
    prompt: { en: 'What is the most abundant protein in the human body?' },
    choices: { en: ['Albumin', 'Keratin', 'Haemoglobin', 'Collagen'] },
    correctIndex: 3,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-universal-plasma',
    prompt: { en: 'Which blood group makes a universal plasma donor?' },
    choices: { en: ['AB', 'O negative', 'O positive', 'A negative'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-carbon-14',
    prompt: { en: 'What is the half-life of carbon-14, roughly?' },
    choices: { en: ['1,600 years', '5,730 years', '12,000 years', '24,000 years'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-third-atmosphere-gas',
    prompt: { en: "Which is the third most abundant gas in Earth's atmosphere?" },
    choices: { en: ['Carbon dioxide', 'Neon', 'Argon', 'Methane'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-titan-moon',
    prompt: { en: 'Titan, the moon with a thick nitrogen atmosphere, orbits which planet?' },
    choices: { en: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'his-hundred-years-war',
    prompt: { en: "How many years did the Hundred Years' War actually last?" },
    choices: { en: ['99', '100', '116', '122'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-defenestration',
    prompt: { en: 'The 1618 Defenestration of Prague triggered which war?' },
    choices: {
      en: ["Thirty Years' War", "Seven Years' War", 'Hussite Wars', 'War of the Spanish Succession'],
    },
    correctIndex: 0,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-adwa',
    prompt: { en: 'Which African state defeated Italy at the Battle of Adwa in 1896?' },
    choices: { en: ['Sudan', 'Morocco', 'Egypt', 'Ethiopia'] },
    correctIndex: 3,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-mohacs',
    prompt: { en: 'At Mohács in 1526, the Ottomans defeated the kingdom of which country?' },
    choices: { en: ['Poland', 'Hungary', 'Serbia', 'Bohemia'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'cul-master-margarita',
    prompt: { en: 'Who wrote The Master and Margarita?' },
    choices: {
      en: ['Vladimir Nabokov', 'Boris Pasternak', 'Mikhail Bulgakov', 'Aleksandr Solzhenitsyn'],
    },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-clocks-thirteen',
    prompt: { en: 'In which novel do the clocks strike thirteen on the opening page?' },
    choices: { en: ['Brave New World', 'Fahrenheit 451', 'We', 'Nineteen Eighty-Four'] },
    correctIndex: 3,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-garden-delights',
    prompt: { en: 'Who painted The Garden of Earthly Delights?' },
    choices: {
      en: ['Pieter Bruegel the Elder', 'Hieronymus Bosch', 'Albrecht Dürer', 'Jan van Eyck'],
    },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-first-best-picture',
    prompt: { en: 'Which film won the first Academy Award for Best Picture?' },
    choices: { en: ['Wings', 'The Jazz Singer', 'Sunrise', 'Metropolis'] },
    correctIndex: 0,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-letter-no-state',
    prompt: { en: 'Which letter appears in no US state name?' },
    choices: { en: ['Z', 'X', 'Q', 'J'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'spo-fencing-golds',
    prompt: { en: 'Which country has won the most Olympic gold medals in fencing?' },
    choices: { en: ['France', 'Italy', 'Hungary', 'Russia'] },
    correctIndex: 1,
    category: 'sport',
    difficulty: 'hard',
  },

  {
    id: 'geo-most-islands',
    prompt: { en: 'Which country has the most islands?' },
    choices: { en: ['Canada', 'Indonesia', 'Sweden', 'Philippines'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-largest-inland-water',
    prompt: { en: "What is the world's largest inland body of water?" },
    choices: { en: ['Lake Superior', 'Caspian Sea', 'Lake Baikal', 'Aral Sea'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-deepest-lake',
    prompt: { en: "What is the world's deepest lake?" },
    choices: { en: ['Lake Tanganyika', 'Caspian Sea', 'Lake Baikal', 'Crater Lake'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-largest-africa-lake',
    prompt: { en: 'What is the largest lake in Africa by surface area?' },
    choices: { en: ['Lake Tanganyika', 'Lake Malawi', 'Lake Chad', 'Lake Victoria'] },
    correctIndex: 3,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'sci-smallest-bone',
    prompt: { en: 'What is the smallest bone in the human body?' },
    choices: { en: ['Stapes', 'Malleus', 'Incus', 'Pisiform'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-longest-bone',
    prompt: { en: 'What is the longest bone in the human body?' },
    choices: { en: ['Tibia', 'Femur', 'Humerus', 'Fibula'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-sideways-planet',
    prompt: { en: 'Which planet rotates on its side, tilted about ninety degrees?' },
    choices: { en: ['Neptune', 'Saturn', 'Uranus', 'Venus'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-universe-element',
    prompt: { en: 'Which element is the most abundant in the universe?' },
    choices: { en: ['Helium', 'Hydrogen', 'Oxygen', 'Carbon'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-penicillin',
    prompt: { en: 'Who discovered penicillin?' },
    choices: { en: ['Louis Pasteur', 'Robert Koch', 'Alexander Fleming', 'Joseph Lister'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-uncertainty',
    prompt: { en: 'Which physicist formulated the uncertainty principle?' },
    choices: { en: ['Niels Bohr', 'Erwin Schrödinger', 'Max Planck', 'Werner Heisenberg'] },
    correctIndex: 3,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'nat-largest-shark',
    prompt: { en: 'What is the largest species of shark?' },
    choices: { en: ['Great white', 'Whale shark', 'Basking shark', 'Tiger shark'] },
    correctIndex: 1,
    category: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'nat-group-of-crows',
    prompt: { en: 'What is the collective noun for a group of crows?' },
    choices: { en: ['A murder', 'A parliament', 'A gaggle', 'A pride'] },
    correctIndex: 0,
    category: 'nature',
    difficulty: 'hard',
  },
  {
    id: 'his-chernobyl',
    prompt: { en: 'In which year did the Chernobyl disaster happen?' },
    choices: { en: ['1982', '1986', '1989', '1991'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-oldest-university',
    prompt: { en: 'Which is the oldest university in continuous operation in Europe?' },
    choices: { en: ['Oxford', 'Bologna', 'Paris', 'Salamanca'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-first-marriage-equality',
    prompt: { en: 'Which country was the first to legalise same-sex marriage?' },
    choices: { en: ['Belgium', 'Canada', 'Netherlands', 'Spain'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-postage-stamp',
    prompt: { en: 'Which country issued the first adhesive postage stamp?' },
    choices: { en: ['France', 'United States', 'United Kingdom', 'Austria'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'cul-divine-comedy',
    prompt: { en: 'Who wrote The Divine Comedy?' },
    choices: { en: ['Petrarch', 'Boccaccio', 'Dante Alighieri', 'Virgil'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-persistence-memory',
    prompt: { en: 'Who painted The Persistence of Memory, with its melting clocks?' },
    choices: { en: ['Salvador Dalí', 'René Magritte', 'Joan Miró', 'Max Ernst'] },
    correctIndex: 0,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-soup-cans',
    prompt: { en: "Who made the Campbell's Soup Cans series?" },
    choices: { en: ['Roy Lichtenstein', 'Andy Warhol', 'Jasper Johns', 'Robert Rauschenberg'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'hard',
  },

  // ─────────────────────────────── BRUTAL ───────────────────────────────
  {
    id: 'geo-burkina-capital',
    prompt: { en: 'What is the capital of Burkina Faso?' },
    choices: { en: ['Bamako', 'Niamey', 'Ouagadougou', 'Lomé'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-nepal-flag',
    prompt: { en: 'Which country has the only national flag that is not a rectangle?' },
    choices: { en: ['Switzerland', 'Nepal', 'Vatican City', 'Bhutan'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-challenger-deep',
    prompt: { en: 'What is the deepest known point in the ocean called?' },
    choices: { en: ['Sirena Deep', 'Horizon Deep', 'Meteor Deep', 'Challenger Deep'] },
    correctIndex: 3,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-russia-time-zones',
    prompt: { en: 'How many time zones does Russia span?' },
    choices: { en: ['9', '11', '12', '8'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'sci-candela',
    prompt: { en: 'Which SI base unit measures luminous intensity?' },
    choices: { en: ['Lumen', 'Lux', 'Candela', 'Watt'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-laser-acronym',
    prompt: { en: "In the acronym LASER, what does the letter S stand for?" },
    choices: { en: ['Stimulated', 'Spectrum', 'Synchronised', 'Static'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-giraffe-vertebrae',
    prompt: { en: 'How many vertebrae are in a giraffe’s neck?' },
    choices: { en: ['7', '12', '20', '32'] },
    correctIndex: 0,
    category: 'nature',
    difficulty: 'brutal',
  },
  {
    id: 'sci-chessboard-squares',
    prompt: { en: 'How many squares of all sizes are there on a chessboard?' },
    choices: { en: ['64', '128', '196', '204'] },
    correctIndex: 3,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-fermat',
    prompt: { en: "Who proved Fermat's Last Theorem?" },
    choices: { en: ['Grigori Perelman', 'Andrew Wiles', 'Terence Tao', 'Paul Erdős'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-perfect-fifth',
    prompt: { en: 'How many semitones make up a perfect fifth?' },
    choices: { en: ['5', '6', '7', '8'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'his-westphalia',
    prompt: { en: "In which year did the Peace of Westphalia end the Thirty Years' War?" },
    choices: { en: ['1618', '1648', '1659', '1683'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-last-western-emperor',
    prompt: { en: 'Who was the last emperor of the Western Roman Empire?' },
    choices: { en: ['Honorius', 'Valentinian III', 'Romulus Augustulus', 'Constantine XI'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-women-vote-first',
    prompt: { en: 'Which country was the first to grant women the national right to vote?' },
    choices: { en: ['Finland', 'Norway', 'New Zealand', 'Australia'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-antikythera',
    prompt: { en: 'The Antikythera mechanism is believed to be an ancient what?' },
    choices: {
      en: ['Water clock', 'Astronomical calculator', 'Musical instrument', 'Navigation compass'],
    },
    correctIndex: 1,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'cul-bluebeard',
    prompt: { en: 'Who composed the opera Bluebeard’s Castle?' },
    choices: { en: ['Zoltán Kodály', 'Béla Bartók', 'Franz Liszt', 'György Ligeti'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'geo-kyrgyzstan-capital',
    prompt: { en: 'What is the capital of Kyrgyzstan?' },
    choices: { en: ['Dushanbe', 'Bishkek', 'Astana', 'Tashkent'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-eleven-languages',
    prompt: { en: 'Which country recognises eleven or more official languages?' },
    choices: { en: ['India', 'Switzerland', 'South Africa', 'Bolivia'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-vexillology',
    prompt: { en: 'What is the study of flags called?' },
    choices: { en: ['Heraldry', 'Vexillology', 'Semiotics', 'Cartography'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'sci-coulomb',
    prompt: { en: 'What is the SI unit of electric charge?' },
    choices: { en: ['Volt', 'Ampere', 'Coulomb', 'Farad'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-largest-moon',
    prompt: { en: 'What is the largest moon in the Solar System?' },
    choices: { en: ['Titan', 'Callisto', 'Ganymede', 'Europa'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-longest-orbit',
    prompt: { en: 'Which planet takes the longest to orbit the Sun?' },
    choices: { en: ['Saturn', 'Uranus', 'Neptune', 'Jupiter'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-olympus-mons',
    prompt: { en: 'On which planet is Olympus Mons, the largest volcano known?' },
    choices: { en: ['Venus', 'Mars', 'Mercury', 'Jupiter'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-first-clone',
    prompt: { en: 'What was the name of the first cloned mammal?' },
    choices: { en: ['Dolly', 'Molly', 'Polly', 'Holly'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-eulers-number',
    prompt: { en: 'Whose constant is approximately 2.718?' },
    choices: { en: ['Gauss', 'Euler', 'Fibonacci', 'Fermat'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'nat-flying-mammal',
    prompt: { en: 'Which is the only mammal capable of true sustained flight?' },
    choices: { en: ['Flying squirrel', 'Bat', 'Colugo', 'Sugar glider'] },
    correctIndex: 1,
    category: 'nature',
    difficulty: 'brutal',
  },
  {
    id: 'nat-largest-invertebrate',
    prompt: { en: 'What is the largest invertebrate on Earth?' },
    choices: { en: ['Giant clam', 'Colossal squid', 'Japanese spider crab', 'Lion’s mane jellyfish'] },
    correctIndex: 1,
    category: 'nature',
    difficulty: 'brutal',
  },
  {
    id: 'his-oldest-parliament',
    prompt: { en: 'Which country has the oldest parliament still in operation?' },
    choices: { en: ['United Kingdom', 'Iceland', 'Switzerland', 'San Marino'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-first-woman-nobel',
    prompt: { en: 'Who was the first woman to win a Nobel Prize?' },
    choices: { en: ['Marie Curie', 'Bertha von Suttner', 'Selma Lagerlöf', 'Irène Joliot-Curie'] },
    correctIndex: 0,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-first-nobel-year',
    prompt: { en: 'In which year was the first Nobel Prize awarded?' },
    choices: { en: ['1895', '1901', '1910', '1918'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'cul-hundred-dollar',
    prompt: { en: 'Whose portrait is on the United States hundred dollar bill?' },
    choices: { en: ['Thomas Jefferson', 'Benjamin Franklin', 'John Adams', 'Alexander Hamilton'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'cul-brandenburg',
    prompt: { en: 'Who composed the Brandenburg Concertos?' },
    choices: { en: ['Handel', 'Vivaldi', 'Bach', 'Telemann'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'cul-etymology',
    prompt: { en: 'What is the study of the origin of words called?' },
    choices: { en: ['Etymology', 'Entomology', 'Phonology', 'Morphology'] },
    correctIndex: 0,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'cul-russian-alphabet',
    prompt: { en: 'How many letters are in the modern Russian alphabet?' },
    choices: { en: ['26', '30', '33', '36'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'cul-general-theory',
    prompt: {
      en: 'Who wrote The General Theory of Employment, Interest and Money?',
    },
    choices: { en: ['Friedrich Hayek', 'Milton Friedman', 'John Maynard Keynes', 'Alfred Marshall'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'brutal',
  },
]
