export type TriviaCategory =
  | 'geography'
  | 'science'
  | 'history'
  | 'culture'
  | 'sport'
  | 'nature'

/**
 * A közönség művelt huszonévesekből áll, ezért nincs "easy" szint.
 *
 * A cél, hogy egy jó csapat is 60-70% körül teljesítsen: ha mindkét autó
 * közel maximumot ér el, a pontszámok nem szóródnak, és a kör
 * gyakorlatilag döntetlen lesz. A szóródás maga a játékmenet.
 */
export type TriviaDifficulty = 'medium' | 'hard' | 'brutal'

export interface TriviaQuestion {
  id: string
  /** A magyar fordítás később kerül bele; a szerkezet már most készen áll rá. */
  prompt: { en: string; hu?: string }
  choices: { en: string[]; hu?: string[] }
  correctIndex: number
  category: TriviaCategory
  difficulty: TriviaDifficulty
}

export const TRIVIA_QUESTIONS: TriviaQuestion[] = [
  // ─────────────────────────────── MEDIUM ───────────────────────────────
  {
    id: 'geo-danube-countries',
    prompt: { en: 'Which river flows through the most countries?' },
    choices: { en: ['Danube', 'Nile', 'Amazon', 'Rhine'] },
    correctIndex: 0,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-longest-coastline',
    prompt: { en: 'Which country has the longest coastline?' },
    choices: { en: ['Russia', 'Canada', 'Indonesia', 'Australia'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-largest-landlocked',
    prompt: { en: 'What is the largest landlocked country by area?' },
    choices: { en: ['Mongolia', 'Chad', 'Kazakhstan', 'Bolivia'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-sea-without-coast',
    prompt: { en: 'Which sea has no coastline at all?' },
    choices: { en: ['Coral Sea', 'Aral Sea', 'Baltic Sea', 'Sargasso Sea'] },
    correctIndex: 3,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'geo-most-unesco',
    prompt: { en: 'Which country has the most UNESCO World Heritage sites?' },
    choices: { en: ['China', 'Italy', 'Spain', 'France'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'medium',
  },
  {
    id: 'sci-highest-melting-metal',
    prompt: { en: 'Which metal has the highest melting point?' },
    choices: { en: ['Platinum', 'Titanium', 'Tungsten', 'Iridium'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-octopus-hearts',
    prompt: { en: 'How many hearts does an octopus have?' },
    choices: { en: ['One', 'Two', 'Three', 'Four'] },
    correctIndex: 2,
    category: 'nature',
    difficulty: 'medium',
  },
  {
    id: 'sci-absolute-zero',
    prompt: { en: 'What is absolute zero in degrees Celsius?' },
    choices: { en: ['−273.15', '−459.67', '−196.00', '−100.00'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-shortest-day',
    prompt: { en: 'Which planet has the shortest day?' },
    choices: { en: ['Mercury', 'Mars', 'Venus', 'Jupiter'] },
    correctIndex: 3,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'sci-cern-2012',
    prompt: { en: 'Which particle was confirmed at CERN in 2012?' },
    choices: { en: ['Neutrino', 'Higgs boson', 'Top quark', 'Muon'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'medium',
  },
  {
    id: 'his-suleiman',
    prompt: { en: 'Which empire did Suleiman the Magnificent rule?' },
    choices: { en: ['Persian', 'Mughal', 'Ottoman', 'Byzantine'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'his-first-roman-emperor',
    prompt: { en: 'Who was the first Roman emperor?' },
    choices: { en: ['Julius Caesar', 'Augustus', 'Tiberius', 'Nero'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'his-turkey-republic',
    prompt: { en: 'In which year was the Republic of Turkey proclaimed?' },
    choices: { en: ['1908', '1918', '1923', '1930'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'medium',
  },
  {
    id: 'cul-solitude',
    prompt: { en: 'Who wrote One Hundred Years of Solitude?' },
    choices: {
      en: ['Jorge Luis Borges', 'Mario Vargas Llosa', 'Gabriel García Márquez', 'Pablo Neruda'],
    },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-rite-of-spring',
    prompt: { en: 'Who composed The Rite of Spring?' },
    choices: { en: ['Claude Debussy', 'Igor Stravinsky', 'Maurice Ravel', 'Béla Bartók'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-seven-samurai',
    prompt: { en: 'Who directed Seven Samurai?' },
    choices: { en: ['Yasujirō Ozu', 'Akira Kurosawa', 'Kenji Mizoguchi', 'Masaki Kobayashi'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'cul-hungarian-family',
    prompt: { en: 'Which language family does Hungarian belong to?' },
    choices: { en: ['Indo-European', 'Turkic', 'Uralic', 'Caucasian'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'medium',
  },
  {
    id: 'spo-snooker-max',
    prompt: { en: 'What is the maximum break in snooker?' },
    choices: { en: ['140', '147', '155', '180'] },
    correctIndex: 1,
    category: 'sport',
    difficulty: 'medium',
  },

  // ──────────────────────────────── HARD ────────────────────────────────
  {
    id: 'geo-most-time-zones',
    prompt: { en: 'Which country spans the most time zones?' },
    choices: { en: ['Russia', 'France', 'United States', 'United Kingdom'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-doubly-landlocked',
    prompt: { en: 'Which country is doubly landlocked, surrounded only by landlocked states?' },
    choices: { en: ['Mongolia', 'Nepal', 'Uzbekistan', 'Bolivia'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-southernmost-capital',
    prompt: { en: 'Which is the southernmost national capital in the world?' },
    choices: { en: ['Canberra', 'Santiago', 'Buenos Aires', 'Wellington'] },
    correctIndex: 3,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-baikal-share',
    prompt: {
      en: "Roughly what share of the world's unfrozen fresh surface water sits in Lake Baikal?",
    },
    choices: { en: ['5%', '10%', '20%', '40%'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'geo-bosphorus',
    prompt: { en: 'Which strait connects the Black Sea to the Sea of Marmara?' },
    choices: { en: ['Dardanelles', 'Bosphorus', 'Kerch Strait', 'Strait of Messina'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'hard',
  },
  {
    id: 'sci-most-abundant-protein',
    prompt: { en: 'What is the most abundant protein in the human body?' },
    choices: { en: ['Albumin', 'Keratin', 'Haemoglobin', 'Collagen'] },
    correctIndex: 3,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-universal-plasma',
    prompt: { en: 'Which blood group makes a universal plasma donor?' },
    choices: { en: ['AB', 'O negative', 'O positive', 'A negative'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-carbon-14',
    prompt: { en: 'What is the half-life of carbon-14, roughly?' },
    choices: { en: ['1,600 years', '5,730 years', '12,000 years', '24,000 years'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-third-atmosphere-gas',
    prompt: { en: "Which is the third most abundant gas in Earth's atmosphere?" },
    choices: { en: ['Carbon dioxide', 'Neon', 'Argon', 'Methane'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'sci-titan-moon',
    prompt: { en: 'Titan, the moon with a thick nitrogen atmosphere, orbits which planet?' },
    choices: { en: ['Jupiter', 'Saturn', 'Uranus', 'Neptune'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'hard',
  },
  {
    id: 'his-hundred-years-war',
    prompt: { en: "How many years did the Hundred Years' War actually last?" },
    choices: { en: ['99', '100', '116', '122'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-defenestration',
    prompt: { en: 'The 1618 Defenestration of Prague triggered which war?' },
    choices: {
      en: ["Thirty Years' War", "Seven Years' War", 'Hussite Wars', 'War of the Spanish Succession'],
    },
    correctIndex: 0,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-adwa',
    prompt: { en: 'Which African state defeated Italy at the Battle of Adwa in 1896?' },
    choices: { en: ['Sudan', 'Morocco', 'Egypt', 'Ethiopia'] },
    correctIndex: 3,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'his-mohacs',
    prompt: { en: 'At Mohács in 1526, the Ottomans defeated the kingdom of which country?' },
    choices: { en: ['Poland', 'Hungary', 'Serbia', 'Bohemia'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'hard',
  },
  {
    id: 'cul-master-margarita',
    prompt: { en: 'Who wrote The Master and Margarita?' },
    choices: {
      en: ['Vladimir Nabokov', 'Boris Pasternak', 'Mikhail Bulgakov', 'Aleksandr Solzhenitsyn'],
    },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-clocks-thirteen',
    prompt: { en: 'In which novel do the clocks strike thirteen on the opening page?' },
    choices: { en: ['Brave New World', 'Fahrenheit 451', 'We', 'Nineteen Eighty-Four'] },
    correctIndex: 3,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-garden-delights',
    prompt: { en: 'Who painted The Garden of Earthly Delights?' },
    choices: {
      en: ['Pieter Bruegel the Elder', 'Hieronymus Bosch', 'Albrecht Dürer', 'Jan van Eyck'],
    },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-first-best-picture',
    prompt: { en: 'Which film won the first Academy Award for Best Picture?' },
    choices: { en: ['Wings', 'The Jazz Singer', 'Sunrise', 'Metropolis'] },
    correctIndex: 0,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'cul-letter-no-state',
    prompt: { en: 'Which letter appears in no US state name?' },
    choices: { en: ['Z', 'X', 'Q', 'J'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'hard',
  },
  {
    id: 'spo-fencing-golds',
    prompt: { en: 'Which country has won the most Olympic gold medals in fencing?' },
    choices: { en: ['France', 'Italy', 'Hungary', 'Russia'] },
    correctIndex: 1,
    category: 'sport',
    difficulty: 'hard',
  },

  // ─────────────────────────────── BRUTAL ───────────────────────────────
  {
    id: 'geo-burkina-capital',
    prompt: { en: 'What is the capital of Burkina Faso?' },
    choices: { en: ['Bamako', 'Niamey', 'Ouagadougou', 'Lomé'] },
    correctIndex: 2,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-nepal-flag',
    prompt: { en: 'Which country has the only national flag that is not a rectangle?' },
    choices: { en: ['Switzerland', 'Nepal', 'Vatican City', 'Bhutan'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-challenger-deep',
    prompt: { en: 'What is the deepest known point in the ocean called?' },
    choices: { en: ['Sirena Deep', 'Horizon Deep', 'Meteor Deep', 'Challenger Deep'] },
    correctIndex: 3,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'geo-russia-time-zones',
    prompt: { en: 'How many time zones does Russia span?' },
    choices: { en: ['9', '11', '12', '8'] },
    correctIndex: 1,
    category: 'geography',
    difficulty: 'brutal',
  },
  {
    id: 'sci-candela',
    prompt: { en: 'Which SI base unit measures luminous intensity?' },
    choices: { en: ['Lumen', 'Lux', 'Candela', 'Watt'] },
    correctIndex: 2,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-laser-acronym',
    prompt: { en: "In the acronym LASER, what does the letter S stand for?" },
    choices: { en: ['Stimulated', 'Spectrum', 'Synchronised', 'Static'] },
    correctIndex: 0,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-giraffe-vertebrae',
    prompt: { en: 'How many vertebrae are in a giraffe’s neck?' },
    choices: { en: ['7', '12', '20', '32'] },
    correctIndex: 0,
    category: 'nature',
    difficulty: 'brutal',
  },
  {
    id: 'sci-chessboard-squares',
    prompt: { en: 'How many squares of all sizes are there on a chessboard?' },
    choices: { en: ['64', '128', '196', '204'] },
    correctIndex: 3,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-fermat',
    prompt: { en: "Who proved Fermat's Last Theorem?" },
    choices: { en: ['Grigori Perelman', 'Andrew Wiles', 'Terence Tao', 'Paul Erdős'] },
    correctIndex: 1,
    category: 'science',
    difficulty: 'brutal',
  },
  {
    id: 'sci-perfect-fifth',
    prompt: { en: 'How many semitones make up a perfect fifth?' },
    choices: { en: ['5', '6', '7', '8'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'his-westphalia',
    prompt: { en: "In which year did the Peace of Westphalia end the Thirty Years' War?" },
    choices: { en: ['1618', '1648', '1659', '1683'] },
    correctIndex: 1,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-last-western-emperor',
    prompt: { en: 'Who was the last emperor of the Western Roman Empire?' },
    choices: { en: ['Honorius', 'Valentinian III', 'Romulus Augustulus', 'Constantine XI'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-women-vote-first',
    prompt: { en: 'Which country was the first to grant women the national right to vote?' },
    choices: { en: ['Finland', 'Norway', 'New Zealand', 'Australia'] },
    correctIndex: 2,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'his-antikythera',
    prompt: { en: 'The Antikythera mechanism is believed to be an ancient what?' },
    choices: {
      en: ['Water clock', 'Astronomical calculator', 'Musical instrument', 'Navigation compass'],
    },
    correctIndex: 1,
    category: 'history',
    difficulty: 'brutal',
  },
  {
    id: 'cul-bluebeard',
    prompt: { en: 'Who composed the opera Bluebeard’s Castle?' },
    choices: { en: ['Zoltán Kodály', 'Béla Bartók', 'Franz Liszt', 'György Ligeti'] },
    correctIndex: 1,
    category: 'culture',
    difficulty: 'brutal',
  },
  {
    id: 'cul-general-theory',
    prompt: {
      en: 'Who wrote The General Theory of Employment, Interest and Money?',
    },
    choices: { en: ['Friedrich Hayek', 'Milton Friedman', 'John Maynard Keynes', 'Alfred Marshall'] },
    correctIndex: 2,
    category: 'culture',
    difficulty: 'brutal',
  },
]
