export const ANIMALS = `
Aardvark, Albatross, Alligator, Alpaca, Antelope, Armadillo, Baboon, Badger,
Bat, Beaver, Bison, Buffalo, Camel, Capybara, Caribou, Cheetah, Chimpanzee,
Chinchilla, Cobra, Cougar, Coyote, Crane, Crocodile, Crow, Deer, Dingo,
Dolphin, Donkey, Dormouse, Eagle, Eel, Elephant, Elk, Falcon, Ferret, Flamingo,
Fox, Gazelle, Gecko, Gibbon, Giraffe, Goat, Goose, Gorilla, Grouse, Hamster,
Hare, Hedgehog, Heron, Hippopotamus, Hornet, Horse, Hyena, Ibex, Iguana,
Jackal, Jaguar, Jellyfish, Kangaroo, Kingfisher, Koala, Lemur, Leopard, Lion,
Llama, Lobster, Lynx, Magpie, Manatee, Mandrill, Marmot, Meerkat, Mole,
Mongoose, Moose, Narwhal, Newt, Nightingale, Ocelot, Octopus, Opossum, Orangutan,
Oryx, Osprey, Ostrich, Otter, Owl, Panda, Pangolin, Panther, Parrot, Peacock,
Pelican, Penguin, Platypus, Porcupine, Puffin, Puma, Quail, Rabbit, Raccoon,
Raven, Reindeer, Rhinoceros, Salamander, Salmon, Scorpion, Seahorse, Seal,
Sloth, Squirrel, Starling, Stingray, Stork, Swan, Tapir, Tiger, Toad, Tortoise,
Toucan, Turtle, Vulture, Wallaby, Walrus, Warthog, Weasel, Whale, Wolf,
Wolverine, Wombat, Woodpecker, Yak, Zebra,
Ant, Anteater, Ape, Barracuda, Bear, Bee, Beetle, Blackbird, Boar, Bull,
Bumblebee, Butterfly, Buzzard, Canary, Carp, Cat, Caterpillar, Catfish,
Chameleon, Chicken, Chipmunk, Clam, Cockatoo, Cockroach, Cow, Crab, Cricket,
Cuckoo, Curlew, Dog, Dove, Dragonfly, Duck, Eagle Owl, Earthworm, Emu, Finch,
Firefly, Flea, Fly, Frog, Gannet, Gerbil, Goldfinch, Goldfish, Grasshopper,
Guinea Pig, Gull, Haddock, Hawk, Hen, Herring, Hummingbird, Impala, Jay,
Kestrel, Kite, Kiwi, Krill, Ladybird, Lamb, Lark, Lizard, Locust, Mackerel,
Mantis, Mink, Minnow, Mole Rat, Monkey, Mosquito, Moth, Mouse, Mule, Nutria,
Ox, Oxpecker, Parakeet, Partridge, Perch, Pheasant, Pig, Pigeon, Pike,
Piranha, Pony, Prawn, Ptarmigan, Python, Quokka, Ram, Rat, Rattlesnake, Ray,
Robin, Rooster, Sandpiper, Sardine, Sawfish, Shark, Sheep, Shrew, Shrimp,
Skunk, Slug, Snail, Snake, Sparrow, Spider, Squid, Stag, Starfish, Stoat,
Sturgeon, Swallow, Swift, Swordfish, Tarantula, Termite, Tern, Thrush, Tick,
Trout, Tuna, Turkey, Viper, Vole, Wasp, Whippet, Woodlouse, Worm, Wren, Zebu
`
