export const CAPITALS = `
Abu Dhabi, Abuja, Accra, Addis Ababa, Algiers, Amman, Amsterdam, Ankara,
Antananarivo, Asuncion, Athens, Baghdad, Baku, Bamako, Bangkok, Beijing,
Beirut, Belgrade, Berlin, Bern, Bogota, Brasilia, Bratislava, Brussels,
Bucharest, Budapest, Buenos Aires, Cairo, Canberra, Caracas, Chisinau,
Colombo, Copenhagen, Dakar, Damascus, Dhaka, Doha, Dublin, Dushanbe, Hanoi,
Harare, Havana, Helsinki, Islamabad, Jakarta, Kabul, Kampala, Kathmandu,
Khartoum, Kiev, Kigali, Kingston, Kuala Lumpur, Kuwait City, Lima, Lisbon,
Ljubljana, London, Luanda, Lusaka, Luxembourg, Madrid, Managua, Manila,
Maputo, Minsk, Monaco, Monrovia, Montevideo, Moscow, Nairobi, Nassau,
New Delhi, Nicosia, Oslo, Ottawa, Panama City, Paris, Phnom Penh, Prague,
Pretoria, Pyongyang, Quito, Rabat, Reykjavik, Riga, Riyadh, Rome, San Jose,
San Marino, Santiago, Sarajevo, Seoul, Singapore, Skopje, Sofia, Stockholm,
Tallinn, Tashkent, Tbilisi, Tehran, Tokyo, Tripoli, Tunis, Ulaanbaatar,
Vaduz, Valletta, Vienna, Vilnius, Warsaw, Washington, Wellington, Yerevan,
Zagreb,
Andorra la Vella, Apia, Ashgabat, Asmara, Astana, Banjul, Basseterre,
Belmopan, Bishkek, Bissau, Brazzaville, Bridgetown, Bujumbura, Castries,
Conakry, Djibouti, Dodoma, Freetown, Funafuti, Gaborone, Georgetown,
Guatemala City, Honiara, Jerusalem, Juba, Kinshasa, Kyiv, Libreville,
Lilongwe, Lome, Majuro, Malabo, Male, Manama, Maseru, Mbabane, Mexico City,
Mogadishu, Moroni, Muscat, Naypyidaw, Ndjamena, Niamey, Nouakchott,
Nukualofa, Ouagadougou, Palikir, Paramaribo, Podgorica, Port au Prince,
Port Louis, Port Moresby, Port of Spain, Port Vila, Porto Novo, Praia,
Pristina, Roseau, Saint Georges, Saint Johns, San Salvador, Sanaa,
Santo Domingo, Sao Tome, Sucre, Suva, Taipei, Tarawa, Tegucigalpa, Thimphu,
Tirana, Vatican City, Victoria, Vientiane, Windhoek, Yamoussoukro, Yaounde
`
