export const FOODS = `
Almond, Anchovy, Apple, Apricot, Artichoke, Asparagus, Aubergine, Avocado,
Bacon, Bagel, Baguette, Banana, Basil, Bean, Beetroot, Blueberry, Bread,
Broccoli, Butter, Cabbage, Cake, Caramel, Carrot, Cashew, Cauliflower, Celery,
Cheese, Cherry, Chestnut, Chickpea, Chilli, Chocolate, Cinnamon, Coconut, Cod,
Coriander, Courgette, Couscous, Crab, Cranberry, Cucumber, Cumin, Curry, Date,
Dumpling, Eggplant, Falafel, Fennel, Fig, Garlic, Ginger, Goulash, Grape,
Grapefruit, Guava, Halloumi, Hazelnut, Honey, Hummus, Jam, Kale, Ketchup,
Kiwi, Lamb, Lasagne, Leek, Lemon, Lentil, Lettuce, Lime, Mackerel, Mango,
Maple, Marzipan, Melon, Mint, Mozzarella, Mushroom, Mussel, Mustard, Noodle,
Nutmeg, Oatmeal, Octopus, Olive, Omelette, Onion, Orange, Oregano, Oyster,
Pancake, Papaya, Paprika, Parmesan, Parsley, Parsnip, Pasta, Peach, Peanut,
Pear, Pepper, Pineapple, Pistachio, Plum, Pomegranate, Popcorn, Pork,
Porridge, Potato, Prawn, Pretzel, Pumpkin, Quinoa, Radish, Raisin, Raspberry,
Rhubarb, Rice, Risotto, Rosemary, Saffron, Sage, Salami, Salmon, Sardine,
Sausage, Scallop, Sesame, Shallot, Spinach, Squid, Steak, Strawberry, Sugar,
Sushi, Tangerine, Thyme, Tofu, Tomato, Truffle, Tuna, Turnip, Vanilla,
Vinegar, Waffle, Walnut, Wasabi, Watermelon, Yoghurt, Zucchini,
Ale, Aioli, Anise, Beef, Beer, Biscuit, Blackberry, Bratwurst, Brie, Brioche,
Brownie, Burger, Burrito, Camembert, Caviar, Champagne, Cheddar, Chicken,
Chips, Chowder, Cider, Clam, Cocoa, Coffee, Cookie, Corn, Cream, Crepe,
Croissant, Custard, Doughnut, Duck, Egg, Endive, Espresso, Feta, Fish, Flour,
Fudge, Gelato, Gin, Gnocchi, Goose, Gouda, Granola, Gravy, Haddock, Ham,
Herring, Hotdog, Ice Cream, Icing, Jelly, Juice, Kebab, Kimchi, Lager,
Lemonade, Liver, Lobster, Macaroni, Marmalade, Mayonnaise, Meatball, Milk,
Muesli, Muffin, Mutton, Nachos, Nectarine, Nougat, Oats, Oil, Okra, Pea,
Pesto, Pie, Pizza, Polenta, Pudding, Quiche, Ramen, Ravioli, Ribs, Roll, Rum,
Rye, Salad, Salsa, Sandwich, Scone, Seaweed, Sorbet, Soup, Spaghetti, Sprout,
Squash, Stew, Stilton, Syrup, Taco, Tapioca, Tarragon, Tart, Tea, Tequila,
Teriyaki, Tilapia, Tiramisu, Toast, Toffee, Tortilla, Treacle, Trifle, Tripe,
Trout, Turkey, Turmeric, Vodka, Wafer, Whisky, Wine, Yam, Yeast, Yogurt,
Zest
`
